### ISSUE TITLE
where is github.com/u2takey/go-utils/sets

### ISSUE THREAD

**Issue by hwh820** [u2takey/ffmpeg-go#41]
where is github.com/u2takey/go-utils/sets 
i can not find them

**Comment by u2takey** [comment]
`github.com/u2takey/go-utils/sets` war changed to private with mistake, sorry for that. fixed now, you can try again

**Comment by hsinhoyeh** [comment]
Thanks for creating this @u2takey , but I still encountered similar errors.
I think maybe you should update your go.mod file as well https://github.com/u2takey/ffmpeg-go/blob/master/go.mod#L9
Otherwise, go get will return errors
```
go get github.com/u2takey/ffmpeg-go
go get: github.com/u2takey/ffmpeg-go@v0.4.0 requires
        github.com/u2takey/go-utils@v0.0.0-20200713025200-4704d09fc2c7: invalid version: unknown revision 4704d09fc2c7
```

**Comment by u2takey** [comment]
> 

go.mod is tidied: https://github.com/u2takey/ffmpeg-go/pull/42, tag add to v0.4.1

**Comment by u2takey** [comment]
> Thanks for creating this @u2takey , but I still encountered similar errors. I think maybe you should update your go.mod file as well https://github.com/u2takey/ffmpeg-go/blob/master/go.mod#L9 Otherwise, go get will return errors
> 
> ```
> go get github.com/u2takey/ffmpeg-go
> go get: github.com/u2takey/ffmpeg-go@v0.4.0 requires
>         github.com/u2takey/go-utils@v0.0.0-20200713025200-4704d09fc2c7: invalid version: unknown revision 4704d09fc2c7
> ```
go.mod is tidied: https://github.com/u2takey/ffmpeg-go/pull/42, tag add to v0.4.1
